In [1]:
!wget https://github.com/HanjieChen/ChallengeClinicalQA/raw/main/medbullets/medbullets_op4.csv

--2025-03-30 19:08:39--  https://github.com/HanjieChen/ChallengeClinicalQA/raw/main/medbullets/medbullets_op4.csv
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/HanjieChen/ChallengeClinicalQA/main/medbullets/medbullets_op4.csv [following]
--2025-03-30 19:08:40--  https://raw.githubusercontent.com/HanjieChen/ChallengeClinicalQA/main/medbullets/medbullets_op4.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1209737 (1.2M) [text/plain]
Saving to: ‘medbullets_op4.csv.2’

medbullets_op4.csv. 100%[===================>]   1.15M  --.-KB/s    in 0.04s

2025-03-30 19:08:40 (30.1 MB/s) - ‘medbullets_op4.csv.2’ saved [1209737/1209737]

In [25]:
import requests

# URLs of the datasets
url_op4 = "https://github.com/HanjieChen/ChallengeClinicalQA/raw/main/medbullets/medbullets_op4.csv"
# Download and save the files
with open("medbullets_op4.csv", "wb") as file:
    file.write(requests.get(url_op4).content)

In [26]:
import pandas as pd

# Load the CSV file
df_op4 = pd.read_csv("medbullets_op4.csv")

# Count duplicates before removing
num_duplicates = df_op4.duplicated(subset=['question']).sum()

# Remove duplicate rows based on the 'question' column, keeping the first occurrence
df_op4 = df_op4.drop_duplicates(subset=['question'], keep='first')

# Display the number of duplicate rows found
print(f"Number of duplicate rows removed: {num_duplicates}")

# Display the first few rows after removing duplicates
print(df_op4.columns)
print(df_op4.head())
print(len(df_op4))

Number of duplicate rows removed: 10
Index(['link', 'question', 'opa', 'opb', 'opc', 'opd', 'answer_idx', 'answer',
       'explanation'],
      dtype='object')
                                               link  \
0                            https://bit.ly/47KxMQs
1                            https://bit.ly/3GZtkBx
2  https://step2.medbullets.com/testview?qid=217175
3                            https://bit.ly/40qTdn2
4                            https://bit.ly/3QOJp1p

                                            question  \
0  A 42-year-old woman is enrolled in a randomize...
1  A 9-year-old girl presents to the emergency de...
2  A 1-year-old girl is brought to a neurologist ...
3  A 17-year-old boy presents to his primary care...
4  A 55-year-old woman is brought to the emergenc...

                                              opa  \
0  AV node > ventricles > atria > Purkinje fibers
1                                 Gastroenteritis
2                             Cardiac rhabdomyoma
3       Continue current therapy for 1 more month
4                           Cerebral salt wasting

                                              opb  \
0  Purkinje fibers > ventricles > atria > AV node
1                       Intentional contamination
2                                        Glaucoma
3                            Dietary intervention
4                                Diuretic overuse

                                              opc  \
0  Purkinje fibers > atria > ventricles > AV node
1                                      Meningitis
2                                    Optic glioma
3                                     Isoretinoin
4                              Primary polydipsia

                                               opd answer_idx  \
0   Purkinje fibers > AV node > ventricles > atria          C
1                          Urinary tract infection          B
2                    Polyostotic fibrous dysplasia          A
3                              Topical antibiotics          D
4  Syndrome of inappropriate anti-diuretic hormone          A

                                           answer  \
0  Purkinje fibers > atria > ventricles > AV node
1                       Intentional contamination
2                             Cardiac rhabdomyoma
3                             Topical antibiotics
4                           Cerebral salt wasting

                                         explanation
0  The conduction velocity of the structures of t...
1  This patient is presenting with repeat sepsis,...
2  This patient with a seizure disorder, ash-leaf...
3  This patient is presenting with persistent acn...
4  This patient presents with a subarachnoid hemo...
298

In [4]:
import openai

def generate_direct_prediction(question, opa, opb, opc, opd):
    """
    Uses GPT-4o to predict the correct answer from a multiple-choice question using separate fields for question and answer choices.
    Returns only the predicted answer in the format: 'B: Femoral artery murmur'
    """
    prompt = f"""
The following is a medical multiple-choice question. It includes a clinical vignette followed by four answer options labeled A, B, C, and D.

Question:
{question}

Choices:
A. {opa}
B. {opb}
C. {opc}
D. {opd}

Your task:
- Select the best answer.
- Respond strictly in the following format: [Letter]: [Answer Text] (e.g., B: Femoral artery murmur)
- Do not explain. Do not repeat the question.
"""

    try:
        client = openai.OpenAI()

        response = client.chat.completions.create(
            model="o3-mini",
            messages=[{"role": "user", "content": prompt}]
        )

        content = response.choices[0].message.content.strip()
        return content

    except Exception as e:
        return "Error"

In [5]:
# Apply the function only to the first 5 rows
df_op4.loc[:4, "gpt_direct_prediction"] = df_op4.loc[:4].apply(
    lambda row: generate_direct_prediction(
        row["question"], row["opa"], row["opb"], row["opc"], row["opd"]
    ),
    axis=1
)
print(df_op4[["question", "gpt_direct_prediction"]].head(5))

                                            question  \
0  A 42-year-old woman is enrolled in a randomize...
1  A 9-year-old girl presents to the emergency de...
2  A 1-year-old girl is brought to a neurologist ...
3  A 17-year-old boy presents to his primary care...
4  A 55-year-old woman is brought to the emergenc...

                               gpt_direct_prediction
0  C: Purkinje fibers > atria > ventricles > AV node
1                       B: Intentional contamination
2                             A: Cardiac rhabdomyoma
3       A: Continue current therapy for 1 more month
4                           A: Cerebral salt wasting

In [6]:
df_op4["gpt_direct_prediction"] = df_op4.apply(
    lambda row: generate_direct_prediction(
        row["question"], row["opa"], row["opb"], row["opc"], row["opd"]
    ),
    axis=1
)

# print(df_op4[["question", "gpt_direct_prediction"]].head(5))

In [7]:
print(df_op4[["question", "gpt_direct_prediction"]].head(15))

                                             question  \
0   A 42-year-old woman is enrolled in a randomize...
1   A 9-year-old girl presents to the emergency de...
2   A 1-year-old girl is brought to a neurologist ...
3   A 17-year-old boy presents to his primary care...
4   A 55-year-old woman is brought to the emergenc...
5   A 2-week-old boy is evaluated by his pediatric...
6   A 1-month-old girl presents to her pediatricia...
7   A newborn boy is evaluated in the hospital nur...
8   A 55-year-old male bodybuilder presents to the...
10  A 57-year-old man presents to the emergency de...
11  A 39-year-old man presents to his doctor for a...
12  An 84-year-old man presents to the physician w...
14  A 51-year-old man presents for his annual well...
15  A 70-year-old woman is brought to the emergenc...
16  A 72-year-old man presents to his primary care...

                                gpt_direct_prediction
0   C: Purkinje fibers > atria > ventricles > AV node
1                        B: Intentional contamination
2                              A: Cardiac rhabdomyoma
3        A: Continue current therapy for 1 more month
4                            A: Cerebral salt wasting
5                                   C: Serial casting
6     C: Obstruction of the extrahepatic biliary tree
7                                               B: 5p
8                                A: Apical lung tumor
10                                         C: Heparin
11                                 D: Viral infection
12                            C: Cervical spondylosis
14                                     D: Propranolol
15                               B: Calcium gluconate
16              D: Wedge pressure lower than expected

In [38]:
# Extract the predicted letter from GPT output (e.g., 'A' from 'A: Cardiac rhabdomyoma')
df_op4["gpt_letter"] = df_op4["gpt_direct_prediction"].astype(str).str.strip().str[0]

# Clean answer_idx to ensure it's a string and uppercase
df_op4["answer_letter"] = df_op4["answer_idx"].astype(str).str.strip().str.upper()

# Compare the predicted letter to the answer letter
df_op4["gpt_letter_match"] = df_op4.apply(
    lambda row: "Correct" if row["gpt_letter"] == row["answer_letter"] else "Incorrect",
    axis=1
)

# Compute accuracy
correct_count = (df_op4["gpt_letter_match"] == "Correct").sum()
total_count = df_op4["gpt_letter_match"].notna().sum()
accuracy = correct_count / total_count if total_count > 0 else 0

# Print results
print(f"Letter-Based Correct Predictions: {correct_count}")
print(f"Total Predictions Compared: {total_count}")
print(f"Letter Match Accuracy: {accuracy:.2%}")

Letter-Based Correct Predictions: 224
Total Predictions Compared: 298
Letter Match Accuracy: 75.17%

## With Bullet Points

In [27]:
import pandas as pd
import re

# Function to process and format question, and count numbered sentences
def process_question(row):
    # Split the question text into sentences
    sentences = re.split(r'(?<=[.!?])\s+', str(row['question']).strip())
    
    if len(sentences) > 1:
        # Number all but the last sentence
        numbered_sentences = [f"{i+1}. {sentence.strip()}" for i, sentence in enumerate(sentences[:-1])]
        formatted_question = "\n".join(numbered_sentences)
        
        # Add a blank line and include the final question sentence without numbering
        formatted_question += f"\n\n{sentences[-1].strip()}"
        num_sentences = len(sentences) - 1
    else:
        formatted_question = sentences[0].strip()
        num_sentences = 0

    # Append formatted answer choices
    options = f"\n\nA. {row['opa'].strip()}\nB. {row['opb'].strip()}\nC. {row['opc'].strip()}\nD. {row['opd'].strip()}"

    return formatted_question + options, num_sentences

# Apply the function and split results into two columns
df_op4[['actual_question', 'number_sentences']] = df_op4.apply(
    lambda row: pd.Series(process_question(row)),
    axis=1
)

# Create bullet_question by replacing numbered steps with dashes
df_op4['bullet_question'] = df_op4['actual_question'] \
    .str.replace(r'^\d+\.\s+', '- ', regex=True) \
    .str.replace(r'\n\d+\.\s+', '\n- ', regex=True)

# Display preview
pd.set_option('display.max_colwidth', None)
print(df_op4[['question', 'actual_question', 'bullet_question', 'number_sentences']].head(2))
pd.reset_option('display.max_colwidth')

# Save the processed DataFrame to CSV
df_op4.to_csv("processed_medbullets_op4.csv", index=False)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     question  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  A 42-year-old woman is enrolled in a randomized controlled trial to study cardiac function in the setting of several different drugs. She is started on verapamil and instructed to exercise at 50% of her VO2 max while several cardiac parameters are being measured. During this experiment, which of the following represents the relative conduction speed through the heart from fastest to slowest?
1  A 9-year-old girl presents to the emergency department with a fever and a change in her behavior. She presented with similar symptoms 6 weeks ago and was treated for an Escherchia coli infection. She also was treated for a urinary tract infection 10 weeks ago. Her mother says that last night her daughter felt ill, and her condition has been worsening. Her daughter experienced a severe headache and had a stiff neck. This morning she was minimally responsive, vomited several times, and produced a small amount of dark cloudy urine. The patient was born at 39 weeks and met all her developmental milestones. She is currently up to date on her vaccinations and did not have infections during early childhood. Her parents are divorced and her father has noted she does not seem to get sick when he takes care of her. Her temperature is 99.5°F (37.5°C), blood pressure is 60/35 mmHg, pulse is 190/min, respirations are 33/min, and oxygen saturation is 98% on room air. The patient is started on intravenous fluids, vasopressors, and broad-spectrum antibiotics. Which of the following is the most appropriate underlying explanation for this patient's presentation?

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             actual_question  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1. A 42-year-old woman is enrolled in a randomized controlled trial to study cardiac function in the setting of several different drugs.\n2. She is started on verapamil and instructed to exercise at 50% of her VO2 max while several cardiac parameters are being measured.\n\nDuring this experiment, which of the following represents the relative conduction speed through the heart from fastest to slowest?\n\nA. AV node > ventricles > atria > Purkinje fibers\nB. Purkinje fibers > ventricles > atria > AV node\nC. Purkinje fibers > atria > ventricles > AV node\nD. Purkinje fibers > AV node > ventricles > atria
1  1. A 9-year-old girl presents to the emergency department with a fever and a change in her behavior.\n2. She presented with similar symptoms 6 weeks ago and was treated for an Escherchia coli infection.\n3. She also was treated for a urinary tract infection 10 weeks ago.\n4. Her mother says that last night her daughter felt ill, and her condition has been worsening.\n5. Her daughter experienced a severe headache and had a stiff neck.\n6. This morning she was minimally responsive, vomited several times, and produced a small amount of dark cloudy urine.\n7. The patient was born at 39 weeks and met all her developmental milestones.\n8. She is currently up to date on her vaccinations and did not have infections during early childhood.\n9. Her parents are divorced and her father has noted she does not seem to get sick when he takes care of her.\n10. Her temperature is 99.5°F (37.5°C), blood pressure is 60/35 mmHg, pulse is 190/min, respirations are 33/min, and oxygen saturation is 98% on room air.\n11. The patient is started on intravenous fluids, vasopressors, and broad-spectrum antibiotics.\n\nWhich of the following is the most appropriate underlying explanation for this patient's presentation?\n\nA. Gastroenteritis\nB. Intentional contamination\nC. Meningitis\nD. Urinary tract infection

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bullet_question  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              - A 42-year-old woman is enrolled in a randomized controlled trial to study cardiac function in the setting of several different drugs.\n- She is started on verapamil and instructed to exercise at 50% of her VO2 max while several cardiac parameters are being measured.\n\nDuring this experiment, which of the following represents the relative conduction speed through the heart from fastest to slowest?\n\nA. AV node > ventricles > atria > Purkinje fibers\nB. Purkinje fibers > ventricles > atria > AV node\nC. Purkinje fibers > atria > ventricles > AV node\nD. Purkinje fibers > AV node > ventricles > atria
1  - A 9-year-old girl presents to the emergency department with a fever and a change in her behavior.\n- She presented with similar symptoms 6 weeks ago and was treated for an Escherchia coli infection.\n- She also was treated for a urinary tract infection 10 weeks ago.\n- Her mother says that last night her daughter felt ill, and her condition has been worsening.\n- Her daughter experienced a severe headache and had a stiff neck.\n- This morning she was minimally responsive, vomited several times, and produced a small amount of dark cloudy urine.\n- The patient was born at 39 weeks and met all her developmental milestones.\n- She is currently up to date on her vaccinations and did not have infections during early childhood.\n- Her parents are divorced and her father has noted she does not seem to get sick when he takes care of her.\n- Her temperature is 99.5°F (37.5°C), blood pressure is 60/35 mmHg, pulse is 190/min, respirations are 33/min, and oxygen saturation is 98% on room air.\n- The patient is started on intravenous fluids, vasopressors, and broad-spectrum antibiotics.\n\nWhich of the following is the most appropriate underlying explanation for this patient's presentation?\n\nA. Gastroenteritis\nB. Intentional contamination\nC. Meningitis\nD. Urinary tract infection

   number_sentences
0                 2
1                11

In [28]:
print(len(df_op4))

298

## GPT 4o Results Direct Prediction

In [29]:
# prompt: use OpenAI GPT4o to extract first columns' paper title. My prompt: Please extract paper title from this sentence.

!pip uninstall -y openai
!pip install --upgrade openai

import openai
print(openai.__version__)
import pandas as pd

# Assuming 'senior_author' DataFrame is loaded and contains a column named 'Paper Title'

# Set your OpenAI API key
openai.# Replace with your actual API key

^C
Traceback (most recent call last):
  File "/data/healthy-ml/scratch/yuexing/anaconda3/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/configuration.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir, enum
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py", line 10, in <module>
    from distutils.command.install import SCHEME_KEYS
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/distutils/command/install.py", line 9, in <module>
    from distutils.core import Command
  File "/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/distutils/core.py", line 19, in <module>
    from distutils.extension import Extension
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 941, in get_code
  File "<frozen importlib._bootstrap_external>", line 1040, in get_data
KeyboardInterrupt
WARNING: Ignoring invalid distribution -illow (/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -illow (/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages)
Requirement already satisfied: openai in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (1.71.0)
Collecting openai
  Downloading openai-1.72.0-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 6.4 MB/s eta 0:00:01
Requirement already satisfied: pydantic<3,>=1.9.0 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from openai) (2.11.2)
Requirement already satisfied: distro<2,>=1.7.0 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from openai) (0.28.1)
Requirement already satisfied: sniffio in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from openai) (1.3.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from openai) (0.9.0)
Requirement already satisfied: tqdm>4 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from openai) (4.66.4)
Requirement already satisfied: anyio<5,>=3.5.0 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from openai) (4.8.0)
Requirement already satisfied: typing-extensions<5,>=4.11 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from openai) (4.13.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from anyio<5,>=3.5.0->openai) (1.2.1)
Requirement already satisfied: idna>=2.8 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: httpcore==1.* in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from httpx<1,>=0.23.0->openai) (1.0.7)
Requirement already satisfied: certifi in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from httpx<1,>=0.23.0->openai) (2024.2.2)
Requirement already satisfied: h11<0.15,>=0.13 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.0)
Requirement already satisfied: pydantic-core==2.33.1 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from pydantic<3,>=1.9.0->openai) (2.33.1)
Requirement already satisfied: annotated-types>=0.6.0 in /data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
WARNING: Ignoring invalid distribution -illow (/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages)
Installing collected packages: openai
  Attempting uninstall: openai
    WARNING: Ignoring invalid distribution -illow (/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages)
    Found existing installation: openai 1.71.0
    Uninstalling openai-1.71.0:
      Successfully uninstalled openai-1.71.0
WARNING: Ignoring invalid distribution -illow (/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages)
Successfully installed openai-1.72.0
WARNING: Ignoring invalid distribution -illow (/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -illow (/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -illow (/data/healthy-ml/scratch/yuexing/anaconda3/lib/python3.9/site-packages)
1.71.0

In [30]:
import openai

def generate_direct_prediction(question_text):
    """
    Uses GPT-4o to predict the correct answer from a multiple-choice question embedded in a single string.
    Returns only the predicted answer in the format: 'B: Femoral artery murmur'
    """
    prompt = f"""
The following is a medical multiple-choice question. It includes a clinical vignette followed by four answer options labeled A, B, C, and D.

{question_text}

Your task:
- Select the best answer.
- Respond strictly in the following format: [Letter]: [Answer Text] (e.g., B: Femoral artery murmur)
- Do not explain. Do not repeat the question.
"""

    try:
        # Initialize OpenAI client
        client = openai.OpenAI(#Set the API key. See the how-to guide for further instructions
        )  # Set your API key
        # Generate response using GPT-4o
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "user", "content": prompt}],
            temperature = 0
        )
        content = response.choices[0].message.content.strip()
        return content
    except Exception as e:
        return "Error"

In [31]:
import openai

def generate_direct_prediction(question_text):
    """
    Uses GPT-4o to predict the correct answer from a multiple-choice question embedded in a single string.
    Returns only the predicted answer in the format: 'B: Femoral artery murmur'
    """
    prompt = f"""
The following is a medical multiple-choice question. It includes a clinical vignette followed by four answer options labeled A, B, C, and D.

{question_text}

Your task:
- Select the best answer.
- Respond strictly in the following format: [Letter]: [Answer Text] (e.g., B: Femoral artery murmur)
- Do not explain. Do not repeat the question.
"""

    try:
        # Initialize OpenAI client
        client = openai.OpenAI(#Set the API key. See the how-to guide for further instructions
        )  # Set your API key
        # Generate response using GPT-4o
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "user", "content": prompt}],
            temperature = 0
        )
        content = response.choices[0].message.content.strip()
        return content
    except Exception as e:
        return "Error"

In [32]:
# Example: first 5 rows for testing
df_subset = df_op4.head(298).copy()

# Apply GPT-4o direct prediction to the 'actual_question' column
df_subset["gpt4o_random1_direct_prediction"] = df_subset["actual_question"].apply(generate_direct_prediction)

# Show results
pd.set_option("display.max_colwidth", None)
display(df_subset[["actual_question", "gpt4o_random1_direct_prediction"]])

,actual_question,gpt4o_random1_direct_prediction
0,"1. A 42-year-old woman is enrolled in a randomized controlled trial to study cardiac function in the setting of several different drugs.\n2. She is started on verapamil and instructed to exercise at 50% of her VO2 max while several cardiac parameters are being measured.\n\nDuring this experiment, which of the following represents the relative conduction speed through the heart from fastest to slowest?\n\nA. AV node > ventricles > atria > Purkinje fibers\nB. Purkinje fibers > ventricles > atria > AV node\nC. Purkinje fibers > atria > ventricles > AV node\nD. Purkinje fibers > AV node > ventricles > atria",B: Purkinje fibers > ventricles > atria > AV node
1,"1. A 9-year-old girl presents to the emergency department with a fever and a change in her behavior.\n2. She presented with similar symptoms 6 weeks ago and was treated for an Escherchia coli infection.\n3. She also was treated for a urinary tract infection 10 weeks ago.\n4. Her mother says that last night her daughter felt ill, and her condition has been worsening.\n5. Her daughter experienced a severe headache and had a stiff neck.\n6. This morning she was minimally responsive, vomited several times, and produced a small amount of dark cloudy urine.\n7. The patient was born at 39 weeks and met all her developmental milestones.\n8. She is currently up to date on her vaccinations and did not have infections during early childhood.\n9. Her parents are divorced and her father has noted she does not seem to get sick when he takes care of her.\n10. Her temperature is 99.5°F (37.5°C), blood pressure is 60/35 mmHg, pulse is 190/min, respirations are 33/min, and oxygen saturation is 98% on room air.\n11. The patient is started on intravenous fluids, vasopressors, and broad-spectrum antibiotics.\n\nWhich of the following is the most appropriate underlying explanation for this patient's presentation?\n\nA. Gastroenteritis\nB. Intentional contamination\nC. Meningitis\nD. Urinary tract infection",B: Intentional contamination
2,"1. A 1-year-old girl is brought to a neurologist due to increasing seizure frequency over the past 2 months.\n2. She recently underwent a neurology evaluation which revealed hypsarrhythmia on electroencephalography (EEG) with a mix of slow waves, multifocal spikes, and asynchrony.\n3. Her parents have noticed the patient occasionally stiffens and spreads her arms at home.\n4. She was born at 38-weeks gestational age without complications.\n5. She has no other medical problems.\n6. Her medications consist of lamotrigine and valproic acid.\n7. Her temperature is 98.3°F (36.8°C), blood pressure is 90/75 mmHg, pulse is 94/min, and respirations are 22/min.\n8. Physical exam reveals innumerable hypopigmented macules on the skin and an irregularly shaped, thickened, and elevated plaque on the lower back.\n\nWhich of the following is most strongly associated with this patient's condition?\n\nA. Cardiac rhabdomyoma\nB. Glaucoma\nC. Optic glioma\nD. Polyostotic fibrous dysplasia",A: Cardiac rhabdomyoma
3,"1. A 17-year-old boy presents to his primary care physician with a chief concern of ""bad"" skin that has not improved despite home remedies.\n2. The patient has had lesions on his face that have persisted since he was 13 years of age.\n3. He has a diet high in refined carbohydrates and has gained 20 pounds since starting high school.\n4. Physical exam is notable for the findings in Figure A.\n5. The patient is started on benzoyl peroxide and topical retinoids.\n6. He returns 1 month later stating that his symptoms are roughly the same.\n\nWhich of the following is the most appropriate next step in management?\n\nA. Continue current therapy for 1 more month\nB. Dietary intervention\nC. Isoretinoin\nD. Topical antibiotics",D: Topical antibiotics
4,"1. A 55-year-old woman is brought to the emergency department by her husband with a 1 hour history of an unremitting headache.\n2. The headache started suddenly while she was eating dinner and she says it feels like the “worst headache of my life.” An emergent CT scan of the head without contrast confirms the diagnosis, and a CT angiogram identifies the source of bleeding.\n3. The patient undergoes surgical management of her condition.\n4. On hospital day 3, she is found to be disoriented to person, place, and time.\n5. She also develops nausea and vomiting.\n6. Her medical problems consist of heart failure for which she takes furosemide, spironolactone, and metoprolol, which were continued at admission.\n7. Her temperature is 99.6°F (37.6°C), blood pressure is 100/60 mmHg, pulse is 112/min, and respirations are 16/min.\n8. Physical examination shows poor skin turgor.\n9. Capillary refill time is 4 seconds.\n10. Serum laboratory results are shown below: Na+: 120 mEq/L Cl-: 92 mEq/L K+: 3.9 mEq/L HCO3-: 26 mEq/L BUN: 32 mg/dL Creatinine: 1.0 mg/dL Serum osmolality is 265 mEq/L and urine osmolality is 340 mEq/L.\n11. Urine sodium is 44 mEq/L.\n\nWhich of the following is the most likely diagnosis?\n\nA. Cerebral salt wasting\nB. Diuretic overuse\nC. Primary polydipsia\nD. Syndrome of inappropriate anti-diuretic hormone",A: Cerebral salt wasting
...,...,...
303,"1. A 42-year-old man presents to the urgent care clinic with low back pain.\n2. He was working on a home improvement project the day prior to presentation when the pain started.\n3. He describes the pain as ""achy and sore."" It is not positional and does not radiate.\n4. He denies fevers, chills, paresthesias, and bowel or bladder incontinence.\n5. He has a history of a distal radius fracture 2 years ago from falling off a ladder.\n6. He drinks 3 alcoholic beverages weekly and denies illicit drug use.\n7. The patient’s temperature is 98.4°F (36.9°C), blood pressure is 124/80 mmHg, pulse is 90/min, and respirations are 16/min.\n8. His body mass index (BMI) is 22.4 kg/m^2.\n9. There is tenderness to palpation of his paravertebral lumbar region bilaterally.\n10. Perineal and dermatomal sensation is symmetric and intact.\n11. Strength is 5/5 to knee flexion/extension and ankle dorsiflexion/plantarflexion.\n12. Patellar and Achilles reflexes are 2+ bilaterally.\n13. Raising either leg while the patient is in the supine position does not elicit any pain.\n\nWhich of the following is the most likely diagnosis?\n\nA. Osteoarthritis\nB. Vertebral compression fracture\nC. Lumbar strain\nD. Disc herniation",C: Lumbar strain
304,"1. A 77-year-old man presents to the emergency department acutely obtunded.\n2. The patient lives alone and was found unresponsive by his son.\n3. Generally, the patient manages his own finances, medications, and works part-time.\n4. He has not been responding to phone calls for the past 3 days.\n5. The patient is unable to offer a history.\n6. He has a past medical history of hypothyroidism, depression, and diabetes.\n7. His temperature is 88.0°F (31.1°C), blood pressure is 92/62 mmHg, pulse is 35/min, respirations are 9/min, and oxygen saturation is 92% on room air.\n8. The patient is cold to the touch and moves all extremities to painful stimuli.\n9. His pupils are reactive and sluggish, and he does not follow commands.\n10. There are no signs of trauma or skin infections.\n11. The patient is started on IV fluids and hydrocortisone, is externally warmed, and is started on a norepinephrine drip.\n12. An ECG is performed as seen in Figure A.\n\nWhich of the following is the most appropriate next step in management?\n\nA. Levothyroxine administration\nB. Free T4 level\nC. Thyroid stimulating hormone and free T4 level\nD. Triiodothyronine administration",A: Levothyroxine administration
305,"1. A 52-year-old G3P3 woman presents to clinic with a 2-year history of urinary incontinence.\n2. She has had frequent, involuntary loss of urine over the last 2 years but presented today because of 10 days of dysuria.\n3. She has been treated for 2 urinary tract infections over the past 6 months.\n4. She does not endorse any loss of urine with coughing or laughter.\n5. She has no chronic medical illnesses and no surgical history.\n6. Her temperature is 99.5°F (37.5°C), blood pressure is 120/80 mmHg, pulse is 92/min, and respirations are 15/min.\n7. Her BMI is 30 kg/m^2.\n8. On pelvic examination, the vagina is dry and atrophic with a 2-cm tender, palpable anterior vaginal mass.\n9. The mass does not change with Valsava maneuver.\n10. Her postvoid residual volume is 60 mL.\n\nWhich of the following is the most likely diagnosis?\n\nA. Urethral diverticulum\nB. Overflow incontinence\nC. Stress urinary incontinence\nD. Pelvic organ prolapse",A: Urethral diverticulum
306,"1. A 48-year-old man presents to the emergency room with a 2-hour history of severe abdominal pain, nausea, and vomiting.\n2. He states that he has not passed gas or had a bowel movement in 4 days and his pain has worsened and become constant over the past 2 hours.\n3. His only medical history includes an appendectomy that he underwent as a child, and he takes no daily medications.\n4. His temperature is 38.5°C (101.3°F), blood pressure is 92/60 mmHg, pulse is 138/min, and respirations are 25/min.\n5. His pulse oximetry is 99% on room air.There are no cardiopulmonary abnormalities on auscultation.\n6. His abdomen is distended and tender in all quadrants, with guarding and rebound present.\n7. He also has increased bowel sounds throughout.\n\nLaboratory results are as follows:\n\nHemoglobin: 11 g/dL\nLeukocyte count: 16,500/mm^3 with normal differential\nPlatelets: 250,000/mm^3\n\nSerum:\nCreatinine: 1.0 mg/dL\nGlucose: 95 mg/dL\nLipase: 45 U/L\nTotal bilirubin: 0.8 mg/dL\nAlkaline phosphatase: 74 U/L\nAspartate aminotransferase (AST, GOT): 32 U/L\nAlanine aminotransferase (ALT, GPT): 45 U/L\nLactate: 7.0 mmol/L\n\nWhich of the following is the most appropriate next step in management?\n\nA. Supportive care, NPO, and intravenous fluids\nB. Urgent surgical intervention\nC. Nasogastric tube placement\nD. CT angiography of the abdomen and pelvis",B: Urgent surgical intervention
307,"1. A 26-year-old woman presents to the emergency department because she feels as though her heart is ""beating out of her chest."" She states that she feels well apart from the discomfort of that sensation.\n2. Her temperature is 97.9°F (36.6°C), blood pressure is 124/84 mmHg, pulse is 180/min, respirations are 22/min, and oxygen saturation is 98% on room air.\n3. An ECG is obtained as seen in Figure A.\n4. After unsuccessful attempts at vagal maneuvers, the emergency physician administers an IV medication.\n5. The effect of the medication wears off in seconds.\n\nWhich of the following is a potential side effect of this medication?\n\nA. Tachycardia\nB. Photosensitivity\nC. Flushing\nD. Seizure",C: Flushing

In [34]:
# display(df_subset[["actual_question", "gpt_direct_prediction"]])

df_subset["answer_idx"] = df_op4.loc[df_subset.index, "answer_idx"]

df_subset["gpt_letter"] = df_subset["gpt4o_random1_direct_prediction"].str.strip().str[0]

df_subset["gpt_correct"] = df_subset.apply(
    lambda row: "Correct" if row["gpt_letter"] == row["answer_idx"] else "Incorrect",
    axis=1
)

correct_count = (df_subset["gpt_correct"] == "Correct").sum()
total_count = df_subset["gpt_correct"].notna().sum()
accuracy = correct_count / total_count

print(f"Correct predictions: {correct_count}")
print(f"Total predictions: {total_count}")
print(f"Accuracy: {accuracy:.2%}")

Correct predictions: 223
Total predictions: 298
Accuracy: 74.83%

## Randomize the Body of the Clinical Vignette

In [35]:
import random

def randomize_case_details(question_block):
    """
    Randomizes the lines of the clinical case except:
    - The first sentence (typically patient presentation)
    - The final question and answer options
    """
    # Split into lines and strip whitespace
    lines = [line.strip() for line in question_block.strip().split("\n") if line.strip()]
    
    # Find the index where the actual question begins (first line with '?')
    question_line_idx = next((i for i, line in enumerate(lines) if "?" in line), None)
    if question_line_idx is None:
        return question_block  # fail-safe: return original if no question found

    # First line: keep intact
    first_line = lines[0]

    # Lines to shuffle: lines between the first and the question line
    middle_lines = lines[1:question_line_idx]

    # Shuffle in-place
    random.shuffle(middle_lines)

    # Final block: reassemble all parts
    randomized_block = "\n".join([first_line] + middle_lines + lines[question_line_idx:])

    return randomized_block

In [36]:
df_subset = df_op4.head(5).copy()

df_op4["actual_question_randomized"] = df_op4["actual_question"].apply(randomize_case_details)
display(df_subset[["actual_question", "actual_question_randomized"]])

,actual_question,actual_question_randomized
0,"1. A 42-year-old woman is enrolled in a randomized controlled trial to study cardiac function in the setting of several different drugs.\n2. She is started on verapamil and instructed to exercise at 50% of her VO2 max while several cardiac parameters are being measured.\n\nDuring this experiment, which of the following represents the relative conduction speed through the heart from fastest to slowest?\n\nA. AV node > ventricles > atria > Purkinje fibers\nB. Purkinje fibers > ventricles > atria > AV node\nC. Purkinje fibers > atria > ventricles > AV node\nD. Purkinje fibers > AV node > ventricles > atria","1. A 42-year-old woman is enrolled in a randomized controlled trial to study cardiac function in the setting of several different drugs.\n2. She is started on verapamil and instructed to exercise at 50% of her VO2 max while several cardiac parameters are being measured.\nDuring this experiment, which of the following represents the relative conduction speed through the heart from fastest to slowest?\nA. AV node > ventricles > atria > Purkinje fibers\nB. Purkinje fibers > ventricles > atria > AV node\nC. Purkinje fibers > atria > ventricles > AV node\nD. Purkinje fibers > AV node > ventricles > atria"
1,"1. A 9-year-old girl presents to the emergency department with a fever and a change in her behavior.\n2. She presented with similar symptoms 6 weeks ago and was treated for an Escherchia coli infection.\n3. She also was treated for a urinary tract infection 10 weeks ago.\n4. Her mother says that last night her daughter felt ill, and her condition has been worsening.\n5. Her daughter experienced a severe headache and had a stiff neck.\n6. This morning she was minimally responsive, vomited several times, and produced a small amount of dark cloudy urine.\n7. The patient was born at 39 weeks and met all her developmental milestones.\n8. She is currently up to date on her vaccinations and did not have infections during early childhood.\n9. Her parents are divorced and her father has noted she does not seem to get sick when he takes care of her.\n10. Her temperature is 99.5°F (37.5°C), blood pressure is 60/35 mmHg, pulse is 190/min, respirations are 33/min, and oxygen saturation is 98% on room air.\n11. The patient is started on intravenous fluids, vasopressors, and broad-spectrum antibiotics.\n\nWhich of the following is the most appropriate underlying explanation for this patient's presentation?\n\nA. Gastroenteritis\nB. Intentional contamination\nC. Meningitis\nD. Urinary tract infection","1. A 9-year-old girl presents to the emergency department with a fever and a change in her behavior.\n8. She is currently up to date on her vaccinations and did not have infections during early childhood.\n3. She also was treated for a urinary tract infection 10 weeks ago.\n7. The patient was born at 39 weeks and met all her developmental milestones.\n6. This morning she was minimally responsive, vomited several times, and produced a small amount of dark cloudy urine.\n4. Her mother says that last night her daughter felt ill, and her condition has been worsening.\n2. She presented with similar symptoms 6 weeks ago and was treated for an Escherchia coli infection.\n10. Her temperature is 99.5°F (37.5°C), blood pressure is 60/35 mmHg, pulse is 190/min, respirations are 33/min, and oxygen saturation is 98% on room air.\n5. Her daughter experienced a severe headache and had a stiff neck.\n9. Her parents are divorced and her father has noted she does not seem to get sick when he takes care of her.\n11. The patient is started on intravenous fluids, vasopressors, and broad-spectrum antibiotics.\nWhich of the following is the most appropriate underlying explanation for this patient's presentation?\nA. Gastroenteritis\nB. Intentional contamination\nC. Meningitis\nD. Urinary tract infection"
2,"1. A 1-year-old girl is brought to a neurologist due to increasing seizure frequency over the past 2 months.\n2. She recently underwent a neurology evaluation which revealed hypsarrhythmia on electroencephalography (EEG) with a mix of slow waves, multifocal spikes, and asynchrony.\n3. Her parents have noticed the patient occasionally stiffens and spreads her arms at home.\n4. She was born at 38-weeks gestational age without complications.\n5. She has no other medical problems.\n6. Her medications consist of lamotrigine and valproic acid.\n7. Her temperature is 98.3°F (36.8°C), blood pressure is 90/75 mmHg, pulse is 94/min, and respirations are 22/min.\n8. Physical exam reveals innumerable hypopigmented macules on the skin and an irregularly shaped, thickened, and elevated plaque on the lower back.\n\nWhich of the following is most strongly associated with this patient's condition?\n\nA. Cardiac rhabdomyoma\nB. Glaucoma\nC. Optic glioma\nD. Polyostotic fibrous dysplasia","1. A 1-year-old girl is brought to a neurologist due to increasing seizure frequency over the past 2 months.\n3. Her parents have noticed the patient occasionally stiffens and spreads her arms at home.\n2. She recently underwent a neurology evaluation which revealed hypsarrhythmia on electroencephalography (EEG) with a mix of slow waves, multifocal spikes, and asynchrony.\n5. She has no other medical problems.\n6. Her medications consist of lamotrigine and valproic acid.\n8. Physical exam reveals innumerable hypopigmented macules on the skin and an irregularly shaped, thickened, and elevated plaque on the lower back.\n7. Her temperature is 98.3°F (36.8°C), blood pressure is 90/75 mmHg, pulse is 94/min, and respirations are 22/min.\n4. She was born at 38-weeks gestational age without complications.\nWhich of the following is most strongly associated with this patient's condition?\nA. Cardiac rhabdomyoma\nB. Glaucoma\nC. Optic glioma\nD. Polyostotic fibrous dysplasia"
3,"1. A 17-year-old boy presents to his primary care physician with a chief concern of ""bad"" skin that has not improved despite home remedies.\n2. The patient has had lesions on his face that have persisted since he was 13 years of age.\n3. He has a diet high in refined carbohydrates and has gained 20 pounds since starting high school.\n4. Physical exam is notable for the findings in Figure A.\n5. The patient is started on benzoyl peroxide and topical retinoids.\n6. He returns 1 month later stating that his symptoms are roughly the same.\n\nWhich of the following is the most appropriate next step in management?\n\nA. Continue current therapy for 1 more month\nB. Dietary intervention\nC. Isoretinoin\nD. Topical antibiotics","1. A 17-year-old boy presents to his primary care physician with a chief concern of ""bad"" skin that has not improved despite home remedies.\n2. The patient has had lesions on his face that have persisted since he was 13 years of age.\n3. He has a diet high in refined carbohydrates and has gained 20 pounds since starting high school.\n5. The patient is started on benzoyl peroxide and topical retinoids.\n6. He returns 1 month later stating that his symptoms are roughly the same.\n4. Physical exam is notable for the findings in Figure A.\nWhich of the following is the most appropriate next step in management?\nA. Continue current therapy for 1 more month\nB. Dietary intervention\nC. Isoretinoin\nD. Topical antibiotics"
4,"1. A 55-year-old woman is brought to the emergency department by her husband with a 1 hour history of an unremitting headache.\n2. The headache started suddenly while she was eating dinner and she says it feels like the “worst headache of my life.” An emergent CT scan of the head without contrast confirms the diagnosis, and a CT angiogram identifies the source of bleeding.\n3. The patient undergoes surgical management of her condition.\n4. On hospital day 3, she is found to be disoriented to person, place, and time.\n5. She also develops nausea and vomiting.\n6. Her medical problems consist of heart failure for which she takes furosemide, spironolactone, and metoprolol, which were continued at admission.\n7. Her temperature is 99.6°F (37.6°C), blood pressure is 100/60 mmHg, pulse is 112/min, and respirations are 16/min.\n8. Physical examination shows poor skin turgor.\n9. Capillary refill time is 4 seconds.\n10. Serum laboratory results are shown below: Na+: 120 mEq/L Cl-: 92 mEq/L K+: 3.9 mEq/L HCO3-: 26 mEq/L BUN: 32 mg/dL Creatinine: 1.0 mg/dL Serum osmolality is 265 mEq/L and urine osmolality is 340 mEq/L.\n11. Urine sodium is 44 mEq/L.\n\nWhich of the following is the most likely diagnosis?\n\nA. Cerebral salt wasting\nB. Diuretic overuse\nC. Primary polydipsia\nD. Syndrome of inappropriate anti-diuretic hormone","1. A 55-year-old woman is brought to the emergency department by her husband with a 1 hour history of an unremitting headache.\n8. Physical examination shows poor skin turgor.\n6. Her medical problems consist of heart failure for which she takes furosemide, spironolactone, and metoprolol, which were continued at admission.\n9. Capillary refill time is 4 seconds.\n2. The headache started suddenly while she was eating dinner and she says it feels like the “worst headache of my life.” An emergent CT scan of the head without contrast confirms the diagnosis, and a CT angiogram identifies the source of bleeding.\n3. The patient undergoes surgical management of her condition.\n5. She also develops nausea and vomiting.\n11. Urine sodium is 44 mEq/L.\n4. On hospital day 3, she is found to be disoriented to person, place, and time.\n7. Her temperature is 99.6°F (37.6°C), blood pressure is 100/60 mmHg, pulse is 112/min, and respirations are 16/min.\n10. Serum laboratory results are shown below: Na+: 120 mEq/L Cl-: 92 mEq/L K+: 3.9 mEq/L HCO3-: 26 mEq/L BUN: 32 mg/dL Creatinine: 1.0 mg/dL Serum osmolality is 265 mEq/L and urine osmolality is 340 mEq/L.\nWhich of the following is the most likely diagnosis?\nA. Cerebral salt wasting\nB. Diuretic overuse\nC. Primary polydipsia\nD. Syndrome of inappropriate anti-diuretic hormone"

In [37]:
# Apply GPT-4o to the randomized questions
df_op4["gpt4o_direct_prediction_randomized"] = df_op4["actual_question_randomized"].apply(generate_direct_prediction)

# Make sure long text is fully visible
import pandas as pd
pd.set_option("display.max_colwidth", None)

# Show a few examples with randomized prompt and prediction
display(df_op4[["actual_question_randomized", "gpt4o_direct_prediction_randomized"]].head())

,actual_question_randomized,gpt4o_direct_prediction_randomized
0,"1. A 42-year-old woman is enrolled in a randomized controlled trial to study cardiac function in the setting of several different drugs.\n2. She is started on verapamil and instructed to exercise at 50% of her VO2 max while several cardiac parameters are being measured.\nDuring this experiment, which of the following represents the relative conduction speed through the heart from fastest to slowest?\nA. AV node > ventricles > atria > Purkinje fibers\nB. Purkinje fibers > ventricles > atria > AV node\nC. Purkinje fibers > atria > ventricles > AV node\nD. Purkinje fibers > AV node > ventricles > atria",B: Purkinje fibers > ventricles > atria > AV node
1,"1. A 9-year-old girl presents to the emergency department with a fever and a change in her behavior.\n4. Her mother says that last night her daughter felt ill, and her condition has been worsening.\n5. Her daughter experienced a severe headache and had a stiff neck.\n2. She presented with similar symptoms 6 weeks ago and was treated for an Escherchia coli infection.\n7. The patient was born at 39 weeks and met all her developmental milestones.\n9. Her parents are divorced and her father has noted she does not seem to get sick when he takes care of her.\n11. The patient is started on intravenous fluids, vasopressors, and broad-spectrum antibiotics.\n3. She also was treated for a urinary tract infection 10 weeks ago.\n8. She is currently up to date on her vaccinations and did not have infections during early childhood.\n6. This morning she was minimally responsive, vomited several times, and produced a small amount of dark cloudy urine.\n10. Her temperature is 99.5°F (37.5°C), blood pressure is 60/35 mmHg, pulse is 190/min, respirations are 33/min, and oxygen saturation is 98% on room air.\nWhich of the following is the most appropriate underlying explanation for this patient's presentation?\nA. Gastroenteritis\nB. Intentional contamination\nC. Meningitis\nD. Urinary tract infection",B: Intentional contamination
2,"1. A 1-year-old girl is brought to a neurologist due to increasing seizure frequency over the past 2 months.\n7. Her temperature is 98.3°F (36.8°C), blood pressure is 90/75 mmHg, pulse is 94/min, and respirations are 22/min.\n2. She recently underwent a neurology evaluation which revealed hypsarrhythmia on electroencephalography (EEG) with a mix of slow waves, multifocal spikes, and asynchrony.\n3. Her parents have noticed the patient occasionally stiffens and spreads her arms at home.\n6. Her medications consist of lamotrigine and valproic acid.\n4. She was born at 38-weeks gestational age without complications.\n5. She has no other medical problems.\n8. Physical exam reveals innumerable hypopigmented macules on the skin and an irregularly shaped, thickened, and elevated plaque on the lower back.\nWhich of the following is most strongly associated with this patient's condition?\nA. Cardiac rhabdomyoma\nB. Glaucoma\nC. Optic glioma\nD. Polyostotic fibrous dysplasia",A: Cardiac rhabdomyoma
3,"1. A 17-year-old boy presents to his primary care physician with a chief concern of ""bad"" skin that has not improved despite home remedies.\n6. He returns 1 month later stating that his symptoms are roughly the same.\n3. He has a diet high in refined carbohydrates and has gained 20 pounds since starting high school.\n2. The patient has had lesions on his face that have persisted since he was 13 years of age.\n4. Physical exam is notable for the findings in Figure A.\n5. The patient is started on benzoyl peroxide and topical retinoids.\nWhich of the following is the most appropriate next step in management?\nA. Continue current therapy for 1 more month\nB. Dietary intervention\nC. Isoretinoin\nD. Topical antibiotics",A: Continue current therapy for 1 more month
4,"1. A 55-year-old woman is brought to the emergency department by her husband with a 1 hour history of an unremitting headache.\n5. She also develops nausea and vomiting.\n3. The patient undergoes surgical management of her condition.\n8. Physical examination shows poor skin turgor.\n10. Serum laboratory results are shown below: Na+: 120 mEq/L Cl-: 92 mEq/L K+: 3.9 mEq/L HCO3-: 26 mEq/L BUN: 32 mg/dL Creatinine: 1.0 mg/dL Serum osmolality is 265 mEq/L and urine osmolality is 340 mEq/L.\n2. The headache started suddenly while she was eating dinner and she says it feels like the “worst headache of my life.” An emergent CT scan of the head without contrast confirms the diagnosis, and a CT angiogram identifies the source of bleeding.\n6. Her medical problems consist of heart failure for which she takes furosemide, spironolactone, and metoprolol, which were continued at admission.\n7. Her temperature is 99.6°F (37.6°C), blood pressure is 100/60 mmHg, pulse is 112/min, and respirations are 16/min.\n11. Urine sodium is 44 mEq/L.\n9. Capillary refill time is 4 seconds.\n4. On hospital day 3, she is found to be disoriented to person, place, and time.\nWhich of the following is the most likely diagnosis?\nA. Cerebral salt wasting\nB. Diuretic overuse\nC. Primary polydipsia\nD. Syndrome of inappropriate anti-diuretic hormone",A: Cerebral salt wasting

In [38]:
# Create a new column with just the predicted answer letter (A/B/C/D)
df_op4["gpt4o_letter_randomized"] = df_op4["gpt4o_direct_prediction_randomized"].str.strip().str[0]

# Compare predictions with actual answers
df_op4["gpt4o_correct_randomized"] = df_op4.apply(
    lambda row: "Correct" if row["gpt4o_letter_randomized"] == row["answer_idx"] else "Incorrect",
    axis=1
)

# Accuracy stats
correct_count = (df_op4["gpt4o_correct_randomized"] == "Correct").sum()
total_count = df_op4["gpt4o_correct_randomized"].notna().sum()
accuracy = correct_count / total_count

# Print stats
print(f"Correct predictions: {correct_count}")
print(f"Total predictions: {total_count}")
print(f"Accuracy: {accuracy:.2%}")

Correct predictions: 217
Total predictions: 298
Accuracy: 72.82%

In [39]:
df_op4[[
    "gpt4o_letter_randomized", 
    "gpt4o_correct_randomized"
]].to_csv("gpt4o_randomized_predictions.csv", index=False)

In [31]:
df_op4[[
    "gpt_letter_randomized", 
    "gpt_correct_randomized"
]].to_csv("o3_randomized_predictions.csv", index=False)

## W/ Reasoning

In [9]:
def get_reasoning_and_answer(bullet_question):
    prompt = f"""
You are a highly capable and careful clinical reasoning assistant. Given a clinical vignette with multiple-choice options, think step by step to identify the most likely correct answer.

{bullet_question}

First, explain your reasoning process in detail as if you were walking a student through the clinical logic step by step.

Then, at the end, write your final answer on a new line in the format:
Final Answer: <number>

Only use one of the digits 0, 1, 2, or 3 to indicate your final choice.
"""

    try:
        client = openai.OpenAI()

        response = client.chat.completions.create(
            model="o3-mini",
            messages=[{"role": "user", "content": prompt}]
        )

        content = response.choices[0].message.content.strip()

        if "Final Answer:" in content:
            parts = content.rsplit("Final Answer:", 1)
            reasoning = parts[0].strip()
            # Protect against empty answer part
            answer_part = parts[1].strip()
            answer = answer_part.split()[0] if answer_part else ""
        else:
            reasoning = content
            answer = ""

        return reasoning, answer

    except Exception as e:
        return "Error during generation", ""

In [11]:
import pandas as pd
from tqdm.notebook import tqdm
import openai

# Setup: result file path and loading progress
results_path = "medbullets_o3_reasoning_results.csv"

try:
    results_df = pd.read_csv(results_path, index_col=0)
    done_indices = set(results_df.index)
    print(f"Resuming from {len(done_indices)} previously completed rows.")
except FileNotFoundError:
    results_df = pd.DataFrame(columns=["o3_reasoning_process", "o3_reasoning_answer"])
    done_indices = set()
    print("Starting fresh.")

# Prediction loop with periodic saving
new_rows = []

for idx in tqdm(df_op4.index):
    if idx in done_indices:
        continue

    bullet_question = df_op4.at[idx, "bullet_question"]

    try:
        reasoning, answer = get_reasoning_and_answer(bullet_question)
    except Exception as e:
        print(f"Error at index {idx}: {e}")
        reasoning, answer = None, None

    new_rows.append((idx, reasoning, answer))

    if len(new_rows) >= 10:  # Save every 10 rows
        temp_df = pd.DataFrame(new_rows, columns=["index", "o3_reasoning_process", "o3_reasoning_answer"])
        temp_df.set_index("index", inplace=True)
        results_df = pd.concat([results_df, temp_df])
        results_df.to_csv(results_path)
        new_rows = []

# Final save if remaining
if new_rows:
    temp_df = pd.DataFrame(new_rows, columns=["index", "o3_reasoning_process", "o3_reasoning_answer"])
    temp_df.set_index("index", inplace=True)
    results_df = pd.concat([results_df, temp_df])
    results_df.to_csv(results_path)

# Merge results into main DataFrame
df_op4 = df_op4.join(results_df, how="left", rsuffix="_new")

# Save full merged output
df_op4.to_csv("medbullets_o3_reasoning_results.csv", index=False)

Starting fresh.

  0%|          | 0/298 [00:00<?, ?it/s]

In [19]:
# Define numeric-to-letter mapping
index_to_letter = {"0": "A", "1": "B", "2": "C", "3": "D"}

# Extract digit, get first column from extract result, then map to A–D
df_op4["o3_reasoning_answer"] = (
    df_op4["o3_reasoning_answer"]
    .astype(str)
    .str.extract(r'(\d)')[0]  # <-- get the first column from the DataFrame
    .map(index_to_letter)
)

# Clean the gold answer column
df_op4["answer_idx"] = df_op4["answer_idx"].astype(str).str.strip().str.upper()

# Compute accuracy
if "o3_reasoning_answer" in df_op4.columns and "answer_idx" in df_op4.columns:
    total = len(df_op4)
    correct = (df_op4["o3_reasoning_answer"] == df_op4["answer_idx"]).sum()
    accuracy = (correct / total) * 100 if total > 0 else 0.0

    print(f"Total Evaluated Examples: {total}")
    print(f"Correct Predictions: {correct}")
    print(f"Accuracy: {accuracy:.2f}%")
else:
    print("Missing required columns: 'o3_reasoning_answer' and/or 'answer_idx'. Evaluation aborted.")

Total Evaluated Examples: 298
Correct Predictions: 255
Accuracy: 85.57%

## 4o

In [22]:
def get_reasoning_and_answer(bullet_question):
    prompt = f"""
You are a highly capable and careful clinical reasoning assistant. Given a clinical vignette with multiple-choice options, think step by step to identify the most likely correct answer.

{bullet_question}

First, explain your reasoning process in detail as if you were walking a student through the clinical logic step by step.

Then, at the end, write your final answer on a new line in the format:
Final Answer: <number>

Only use one of the digits 0, 1, 2, or 3 to indicate your final choice.
"""

    try:
        client = openai.OpenAI()

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "user", "content": prompt}],
            temperature = 0
        )

        content = response.choices[0].message.content.strip()

        if "Final Answer:" in content:
            parts = content.rsplit("Final Answer:", 1)
            reasoning = parts[0].strip()
            # Protect against empty answer part
            answer_part = parts[1].strip()
            answer = answer_part.split()[0] if answer_part else ""
        else:
            reasoning = content
            answer = ""

        return reasoning, answer

    except Exception as e:
        return "Error during generation", ""

In [23]:
import pandas as pd
from tqdm.notebook import tqdm
import openai

# Path to save intermediate and final results
results_path = "medbullets_4o_reasoning_results.csv"

# Try loading previous results to resume from where it left off
try:
    results_df = pd.read_csv(results_path, index_col=0)
    done_indices = set(results_df.index)
    print(f"Resuming from {len(done_indices)} previously completed rows.")
except FileNotFoundError:
    results_df = pd.DataFrame(columns=["4o_reasoning_process", "4o_reasoning_answer"])
    done_indices = set()
    print("Starting fresh.")

# Collect new results in batches
new_rows = []

for idx in tqdm(df_op4.index):
    if idx in done_indices:
        continue

    bullet_question = df_op4.at[idx, "bullet_question"]

    try:
        reasoning, answer = get_reasoning_and_answer(bullet_question)
    except Exception as e:
        print(f"Error at index {idx}: {e}")
        reasoning, answer = "Error during generation", ""

    new_rows.append((idx, reasoning, answer))

    if len(new_rows) >= 10:
        temp_df = pd.DataFrame(new_rows, columns=["index", "4o_reasoning_process", "4o_reasoning_answer"])
        temp_df.set_index("index", inplace=True)
        results_df = pd.concat([results_df, temp_df])
        results_df.to_csv(results_path)
        new_rows = []

# Save any remaining predictions
if new_rows:
    temp_df = pd.DataFrame(new_rows, columns=["index", "4o_reasoning_process", "4o_reasoning_answer"])
    temp_df.set_index("index", inplace=True)
    results_df = pd.concat([results_df, temp_df])
    results_df.to_csv(results_path)

# Merge predictions back into main dataset
df_op4 = df_op4.join(results_df, how="left", rsuffix="_new")

# Save full merged DataFrame
df_op4.to_csv("medbullets_4o_reasoning_results.csv", index=False)

Starting fresh.

  0%|          | 0/298 [00:00<?, ?it/s]

In [24]:
# Define numeric-to-letter mapping
index_to_letter = {"0": "A", "1": "B", "2": "C", "3": "D"}

# Extract digit from '4o_reasoning_answer' and map it to A–D
df_op4["4o_reasoning_answer"] = (
    df_op4["4o_reasoning_answer"]
    .astype(str)
    .str.extract(r'(\d)')[0]  # Take the first (and only) capture group
    .map(index_to_letter)
)

# Clean the reference answer column
df_op4["answer_idx"] = df_op4["answer_idx"].astype(str).str.strip().str.upper()

# Compute and display accuracy
if "4o_reasoning_answer" in df_op4.columns and "answer_idx" in df_op4.columns:
    total = len(df_op4)
    correct = (df_op4["4o_reasoning_answer"] == df_op4["answer_idx"]).sum()
    accuracy = (correct / total) * 100 if total > 0 else 0.0

    print(f"Total Evaluated Examples: {total}")
    print(f"Correct Predictions: {correct}")
    print(f"Accuracy: {accuracy:.2f}%")
else:
    print("Missing required columns: '4o_reasoning_answer' and/or 'answer_idx'. Evaluation aborted.")

Total Evaluated Examples: 298
Correct Predictions: 238
Accuracy: 79.87%

## Llama Results Direct Prediction

In [14]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import os
from huggingface_hub import login

In [71]:
# Load Llama 3.1 7B Instruct model and tokenizer
model_name = "meta-llama/Llama-3.1-8B-Instruct"
hf_token = os.getenv("HF_TOKEN")

tokenizer = AutoTokenizer.from_pretrained(model_name, token=hf_token)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
    token=hf_token
)

# Verify Model Loading
print("Model and tokenizer loaded successfully!")

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some parameters are on the meta device because they were offloaded to the cpu.

Model and tokenizer loaded successfully!

In [72]:
def score_option_from_prompt(prompt, option_text):
    """
    Scores a full prompt + specific answer option using the model's log-likelihood.
    """
    full_prompt = f"{prompt}\nAnswer: {option_text}"
    inputs = tokenizer(full_prompt, return_tensors="pt").to("cuda")
    with torch.no_grad():
        outputs = model(**inputs, labels=inputs["input_ids"])
    return -outputs.loss.item()  # higher is better

In [73]:
def get_best_answer_scored(row):
    prompt = row["actual_question"]

    # Score each choice independently
    scores = {
        "A": score_option_from_prompt(prompt, row["opa"]),
        "B": score_option_from_prompt(prompt, row["opb"]),
        "C": score_option_from_prompt(prompt, row["opc"]),
        "D": score_option_from_prompt(prompt, row["opd"])
    }

    best_letter = max(scores, key=scores.get)
    best_text = {
        "A": row["opa"],
        "B": row["opb"],
        "C": row["opc"],
        "D": row["opd"]
    }[best_letter]

    return pd.Series([best_letter, best_text])

In [75]:
import pandas as pd

# Make sure all content is shown (especially for long clinical questions/answers)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

# Show selected columns
display(df_subset[["actual_question", "Llama_letter", "Llama_answer"]])

,actual_question,Llama_letter,Llama_answer
0,"- A 42-year-old woman is enrolled in a randomized controlled trial to study cardiac function in the setting of several different drugs.\n- She is started on verapamil and instructed to exercise at 50% of her VO2 max while several cardiac parameters are being measured.\n\nDuring this experiment, which of the following represents the relative conduction speed through the heart from fastest to slowest?\n\n- A: AV node > ventricles > atria > Purkinje fibers\n- B: Purkinje fibers > ventricles > atria > AV node\n- C: Purkinje fibers > atria > ventricles > AV node\n- D: Purkinje fibers > AV node > ventricles > atria",C,Purkinje fibers > atria > ventricles > AV node
1,"- A 9-year-old girl presents to the emergency department with a fever and a change in her behavior.\n- She presented with similar symptoms 6 weeks ago and was treated for an Escherchia coli infection.\n- She also was treated for a urinary tract infection 10 weeks ago.\n- Her mother says that last night her daughter felt ill, and her condition has been worsening.\n- Her daughter experienced a severe headache and had a stiff neck.\n- This morning she was minimally responsive, vomited several times, and produced a small amount of dark cloudy urine.\n- The patient was born at 39 weeks and met all her developmental milestones.\n- She is currently up to date on her vaccinations and did not have infections during early childhood.\n- Her parents are divorced and her father has noted she does not seem to get sick when he takes care of her.\n- Her temperature is 99.5°F (37.5°C), blood pressure is 60/35 mmHg, pulse is 190/min, respirations are 33/min, and oxygen saturation is 98% on room air.\n- The patient is started on intravenous fluids, vasopressors, and broad-spectrum antibiotics.\n\nWhich of the following is the most appropriate underlying explanation for this patient's presentation?\n\n- A: Gastroenteritis\n- B: Intentional contamination\n- C: Meningitis\n- D: Urinary tract infection",C,Meningitis
2,"- A 1-year-old girl is brought to a neurologist due to increasing seizure frequency over the past 2 months.\n- She recently underwent a neurology evaluation which revealed hypsarrhythmia on electroencephalography (EEG) with a mix of slow waves, multifocal spikes, and asynchrony.\n- Her parents have noticed the patient occasionally stiffens and spreads her arms at home.\n- She was born at 38-weeks gestational age without complications.\n- She has no other medical problems.\n- Her medications consist of lamotrigine and valproic acid.\n- Her temperature is 98.3°F (36.8°C), blood pressure is 90/75 mmHg, pulse is 94/min, and respirations are 22/min.\n- Physical exam reveals innumerable hypopigmented macules on the skin and an irregularly shaped, thickened, and elevated plaque on the lower back.\n\nWhich of the following is most strongly associated with this patient's condition?\n\n- A: Cardiac rhabdomyoma\n- B: Glaucoma\n- C: Optic glioma\n- D: Polyostotic fibrous dysplasia",C,Optic glioma
3,"- A 17-year-old boy presents to his primary care physician with a chief concern of ""bad"" skin that has not improved despite home remedies.\n- The patient has had lesions on his face that have persisted since he was 13 years of age.\n- He has a diet high in refined carbohydrates and has gained 20 pounds since starting high school.\n- Physical exam is notable for the findings in Figure A.\n- The patient is started on benzoyl peroxide and topical retinoids.\n- He returns 1 month later stating that his symptoms are roughly the same.\n\nWhich of the following is the most appropriate next step in management?\n\n- A: Continue current therapy for 1 more month\n- B: Dietary intervention\n- C: Isoretinoin\n- D: Topical antibiotics",C,Isoretinoin
4,"- A 55-year-old woman is brought to the emergency department by her husband with a 1 hour history of an unremitting headache.\n- The headache started suddenly while she was eating dinner and she says it feels like the “worst headache of my life.” An emergent CT scan of the head without contrast confirms the diagnosis, and a CT angiogram identifies the source of bleeding.\n- The patient undergoes surgical management of her condition.\n- On hospital day 3, she is found to be disoriented to person, place, and time.\n- She also develops nausea and vomiting.\n- Her medical problems consist of heart failure for which she takes furosemide, spironolactone, and metoprolol, which were continued at admission.\n- Her temperature is 99.6°F (37.6°C), blood pressure is 100/60 mmHg, pulse is 112/min, and respirations are 16/min.\n- Physical examination shows poor skin turgor.\n- Capillary refill time is 4 seconds.\n- Serum laboratory results are shown below: Na+: 120 mEq/L Cl-: 92 mEq/L K+: 3.9 mEq/L HCO3-: 26 mEq/L BUN: 32 mg/dL Creatinine: 1.0 mg/dL Serum osmolality is 265 mEq/L and urine osmolality is 340 mEq/L.\n- Urine sodium is 44 mEq/L.\n\nWhich of the following is the most likely diagnosis?\n\n- A: Cerebral salt wasting\n- B: Diuretic overuse\n- C: Primary polydipsia\n- D: Syndrome of inappropriate anti-diuretic hormone",C,Primary polydipsia
5,"- A 2-week-old boy is evaluated by his pediatrician for abnormal feet.\n- The patient was born at 39 weeks via vaginal delivery to a G1P1 29-year-old woman.\n- The patient has been breastfeeding and producing 5 stools/day.\n- He is otherwise healthy.\n- His temperature is 99.5°F (37.5°C), blood pressure is 60/38 mmHg, pulse is 150/min, respirations are 24/min, and oxygen saturation is 98% on room air.\n- A cardiopulmonary exam is notable for a benign flow murmur.\n- A musculoskeletal exam reveals the findings shown in Figure A.\n\nWhich of the following is the most appropriate next step in management?\n\n- A: Botulinum toxin injections\n- B: Reassurance and reassessment in 1 month\n- C: Serial casting\n- D: Surgical pinning",C,Serial casting
6,"- A 1-month-old girl presents to her pediatrician with her mother.\n- The patient was born at 38 weeks gestation via Caesarean section for cervical incompetence.\n- The patient’s mother has no complaints.\n- The child had a runny nose and cough for a few days last week.\n- The patient’s mother endorses decreased appetite during the aforementioned illness which has now returned to baseline.\n- The patient’s family history is significant for an older brother with glucose-6-phosphate dehydrogenase (G6PD) deficiency and a maternal uncle with cirrhosis secondary to chronic hepatitis B.\n- On physical exam, the patient has scleral icterus and dark urine staining her diaper.\n\nLaboratory testing reveals the following: Serum: Na+: 137 mEq/L Cl-: 102 mEq/L K+: 4.2 mEq/L HCO3-: 24 mEq/L Urea nitrogen: 12 mg/dL Glucose: 96 mg/dL Creatinine: 0.36 mg/dL Alkaline phosphatase: 146 U/L Aspartate aminotransferase (AST): 86 U/L Alanine aminotransferase (ALT): 76 U/L Total bilirubin: 4.6 mg/dL Direct bilirubin: 3.8 mg/dL Which of the following is the most likely diagnosis?\n\n- A: Decreased metabolism of bilirubin\n- B: Increased enterohepatic circulation of bilirubin\n- C: Obstruction of the extrahepatic biliary tree\n- D: Obstruction of the intrahepatic biliary tree",C,Obstruction of the extrahepatic biliary tree
7,"- A newborn boy is evaluated in the hospital nursery 2 hours after birth.\n- The patient was born at 39 weeks of gestation to a 30-year-old primigravid via vaginal delivery.\n- The patient’s mother received routine prenatal care and the pregnancy was uncomplicated.\n- The patient’s anatomy ultrasound at 20 weeks of gestation was unremarkable.\n- The patient’s mother denies any family history of genetic diseases.\n- The patient’s APGAR scores were notable for poor muscle tone at both 1 and 5 minutes of life.\n- The patient’s birth weight is 2.6 kg (5 lb 11 oz), which is at the 5th percentile.\n- His height and head circumference are in the 15th and 3rd percentile, respectively.\n- His temperature is 97.1°F (36.2°C), blood pressure is 57/42 mmHg, pulse is 140/min, and respirations are 38/min.\n- On physical exam, the patient has a wide nasal bridge, down slanting palpebral fissures, and widely spaced eyes.\n- He has good respiratory effort with a high-pitched cry.\n\nThis patient is most likely to have experienced a deletion on which of the following chromosomes?\n\n- A: 4p\n- B: 5p\n- C: 7q\n- D: 15q",C,7q
8,"- A 55-year-old male bodybuilder presents to the emergency department with weakness of his right arm.\n- The patient states he has experienced these symptoms for a few weeks; however, today his hand felt so weak he dropped his cup of tea.\n- The patient has a medical history of diabetes.\n- He drinks 2-7 alcoholic drinks per day and has smoked 2 packs of cigarettes per day since he was 25.\n- The patient uses anabolic steroids.\n- He has lost 17 pounds since he last came to the emergency department 1 month ago.\n- His temperature is 99.5°F (37.5°C), blood pressure is 177/108 mmHg, pulse is 90/min, respirations are 17/min, and oxygen saturation is 98% on room air.\n- Physical exam reveals decreased sensation in the right arm and 2/5 strength in the right arm and 5/5 strength in in the left arm.\n- The patient states that he is experiencing a dull aching and burning pain in his right arm during the exam.\n- Symptoms are not changed with changes in head and neck position.\n\nWhich of the following is the most likely diagnosis?\n\n- A: Apical lung tumor\n- B: Brachial plexopathy\n- C: Cerebral infarction\n- D: Scalenus anticus syndrome",C,Cerebral infarction
10,"- A 57-year-old man presents to the emergency department for shortness of breath.\n- He was riding the train home from a business conference when his symptoms began.\n- The patient has a medical history of obesity, diabetes, diabetic nephropathy, hypertension, and a 40-pack-year smoking history.\n- His current medications include atorvastatin, lisinopril, insulin, metformin, and nicotine gum.\n- His temperature is 99.5°F (37.5°C), blood pressure is 130/87 mmHg, pulse is 120/min, respirations are 15/min, and oxygen saturation is 93% on room air.\n- An ECG is ordered as seen in Figure A.\n- A chest radiograph is ordered as seen in Figure B.\n- Laboratory values are ordered as seen below: Serum: Na+: 137 mEq/L Cl-: 105 mEq/L K+: 4.1 mEq/L HCO3-: 24 mEq/L BUN: 22 mg/dL Glucose: 129 mg/dL Creatinine: 1.2 mg/dL Ca2+: 10.1 mg/dL AST: 11 U/L ALT: 12 U/L On physical exam, the patient appears to be in distress.\n- His cardiac exam is notable for tachycardia.\n- Pulmonary exam reveals bilateral air movement without any wheezes or crackles.\n- The patient's right lower extremity appears mildly inflamed, and palpation of the calf elicits pain.\n\nWhich of the following is the most appropriate next step in management?\n\n- A: Aspirin\n- B: Cardiac troponins\n- C: Heparin\n- D: Ventilation perfusion scan",C,Heparin